/users/me:
  controller: Users
  action: me
  method: GET
  middlewares:
    - Auth

/users/login:
  controller: Users
  action: login
  method: POST

/users/register:
  controller: Users
  action: register
  method: POST

/users/{id}:
  controller: Users
  action: show
  method: GET
  middlewares:
    - Auth



/comments/{id}:
  controller: Comments
  action: getById
  method: GET

/comments:
  controller: Comments
  action: list
  method: GET

/comments:
  controller: Comments
  action: create
  method: POST

/comments:
  controller: Comments
  action: update
  method: PUT

/comments:
  controller: Comments
  action: delete
  method: DELETE

/:
  controller: Main
  action: index
  method: GET

/contact:
  controller: Main
  action: contact
  method: GET

/login:
  controller: Auth
  action: login
  method: GET

/logout:
  controller: Auth
  action: logout
  method: GET

/register:
  controller: Auth
  action: register
  method: GET

# ADMIN / BACK-OFFICE

/admin/login:
  controller: Auth
  action: login
  method: GET

/admin:
  controller: Main
  action: dashboard
  method: GET

# ROLES
/roles/create:
  controller: Roles
  action: create
  method: POST

/roles/update/{id}: 
  controller: Roles
  action: update
  method: PUT

/roles/delete/{id}:
  controller: Roles
  action: destroy
  method: DELETE