/users/delete:
  controller: Users
  action: deleteMass
  method: DELETE

/users/me:
  controller: Users
  action: me
  method: GET
  middlewares:
    - Auth

/users/login:
  controller: Users
  action: login
  method: POST

/users/register:
  controller: Users
  action: register
  method: POST

/users/{id}:
  controller: Users
  action: show
  method: GET
  middlewares:
    - Auth

/:
  controller: Main
  action: index
  method: GET

/contact:
  controller: Main
  action: contact
  method: GET

/login:
  controller: Auth
  action: login
  method: GET

/logout:
  controller: Auth
  action: logout
  method: GET

/register:
  controller: Auth
  action: register
  method: GET

# ADMIN / BACK-OFFICE

/admin/login:
  controller: Auth
  action: login
  method: GET

/admin:
  controller: Main
  action: dashboard
  method: GET
